version: '3.9'
services:
  spam-api:
    build: .
    container_name: spam-email-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
